<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="ugv_pioneer_like">

  <xacro:property name="pi" value="3.141592653589793"/>
  <xacro:property name="base_length" value="0.45"/>
  <xacro:property name="base_width"  value="0.32"/>
  <xacro:property name="base_height" value="0.12"/>

  <xacro:property name="wheel_radius" value="0.095"/>
  <xacro:property name="wheel_width"  value="0.035"/>
  <xacro:property name="wheel_sep"    value="0.30"/>

  <material name="Grey"><color rgba="0.6 0.6 0.6 1"/></material>
  <material name="Black"><color rgba="0.1 0.1 0.1 1"/></material>

  <link name="base_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="12.0"/>
      <inertia ixx="0.30" ixy="0" ixz="0" iyy="0.40" iyz="0" izz="0.50"/>
    </inertial>
    <visual>
      <origin xyz="0 0 ${base_height/2.0}" rpy="0 0 0"/>
      <geometry><box size="${base_length} ${base_width} ${base_height}"/></geometry>
      <material name="Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${base_height/2.0}" rpy="0 0 0"/>
      <geometry><box size="${base_length} ${base_width} ${base_height}"/></geometry>
    </collision>
  </link>

  <link name="left_wheel_link">
    <inertial><origin xyz="0 0 0"/><mass value="1.0"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 ${pi/2.0} 0"/>
      <geometry><cylinder radius="${wheel_radius}" length="${wheel_width}"/></geometry>
      <material name="Black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 ${pi/2.0} 0"/>
      <geometry><cylinder radius="${wheel_radius}" length="${wheel_width}"/></geometry>
    </collision>
  </link>

  <link name="right_wheel_link">
    <inertial><origin xyz="0 0 0"/><mass value="1.0"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 ${pi/2.0} 0"/>
      <geometry><cylinder radius="${wheel_radius}" length="${wheel_width}"/></geometry>
      <material name="Black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 ${pi/2.0} 0"/>
      <geometry><cylinder radius="${wheel_radius}" length="${wheel_width}"/></geometry>
    </collision>
  </link>

  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel_link"/>
    <origin xyz="0 ${wheel_sep/2.0} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel_link"/>
    <origin xyz="0 -${wheel_sep/2.0} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <link name="caster_link">
    <inertial><origin xyz="0 0 0"/><mass value="0.2"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
    <visual><geometry><sphere radius="0.035"/></geometry><material name="Black"/></visual>
    <collision><geometry><sphere radius="0.035"/></geometry></collision>
  </link>

  <joint name="caster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_link"/>
    <origin xyz="-0.18 0 0.035" rpy="0 0 0"/>
  </joint>

  <link name="lidar_link">
    <visual>
      <geometry><cylinder radius="0.04" length="0.05"/></geometry>
      <material name="Black"/>
    </visual>
  </link>

  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="0.18 0 0.18" rpy="0 0 0"/>
  </joint>

  <gazebo reference="left_wheel_link"><mu1>1.2</mu1><mu2>1.2</mu2><kp>1e6</kp><kd>1</kd></gazebo>
  <gazebo reference="right_wheel_link"><mu1>1.2</mu1><mu2>1.2</mu2><kp>1e6</kp><kd>1</kd></gazebo>

  <gazebo>
    <plugin filename="libgz-sim-diff-drive-system.so" name="gz::sim::systems::DiffDrive">
      <left_joint>left_wheel_joint</left_joint>
      <right_joint>right_wheel_joint</right_joint>
      <wheel_separation>${wheel_sep}</wheel_separation>
      <wheel_radius>${wheel_radius}</wheel_radius>
      <topic>/cmd_vel</topic>
      <odom_topic>/odom</odom_topic>
      <frame_id>odom</frame_id>
      <child_frame_id>base_link</child_frame_id>
      <odom_publish_frequency>30</odom_publish_frequency>
    </plugin>
  </gazebo>

  <gazebo reference="lidar_link">
    <sensor name="lidar" type="gpu_ray">
      <update_rate>10</update_rate>
      <ray>
        <scan><horizontal><samples>720</samples><min_angle>-3.14159</min_angle><max_angle>3.14159</max_angle></horizontal></scan>
        <range><min>0.12</min><max>12.0</max></range>
      </ray>
      <topic>/scan</topic>
      <visualize>true</visualize>
    </sensor>
  </gazebo>

</robot>
